package sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2020-04-08T19:13:08.895Z
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", name = "IRegistSignPort")
@XmlSeeAlso({ObjectFactory.class})
public interface IRegistSignPort {

    @WebResult(name = "IdentificationUtilisateur", targetNamespace = "")
    @RequestWrapper(localName = "EnregistrerBeneficiaire", targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", className = "sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign.EnregistrerBeneficiaire")
    @WebMethod(operationName = "EnregistrerBeneficiaire", action = "urn:EnregistrerSigner")
    @ResponseWrapper(localName = "EnregistrerBeneficiaireResponse", targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", className = "sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign.EnregistrerBeneficiaireResponse")
    public java.lang.String enregistrerBeneficiaire(
        @WebParam(name = "prenom_nom", targetNamespace = "")
        java.lang.String prenomNom,
        @WebParam(name = "code_pin", targetNamespace = "")
        java.lang.String codePin,
        @WebParam(name = "numero_cni", targetNamespace = "")
        java.lang.String numeroCni,
        @WebParam(name = "IdAppAppelant", targetNamespace = "")
        long idAppAppelant
    );

    @WebResult(name = "sortie", targetNamespace = "")
    @RequestWrapper(localName = "SignatureBeneficiaire", targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", className = "sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign.SignatureBeneficiaire")
    @WebMethod(operationName = "SignatureBeneficiaire", action = "urn:SignatureBeneficiaire")
    @ResponseWrapper(localName = "SignatureBeneficiaireResponse", targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", className = "sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign.SignatureBeneficiaireResponse")
    public SignatureResult signatureBeneficiaire(
        @WebParam(name = "user_id", targetNamespace = "")
        long userId,
        @WebParam(name = "document_a_signer", targetNamespace = "")
        byte[] documentASigner
    );

    @WebResult(name = "statutEnrolement", targetNamespace = "")
    @RequestWrapper(localName = "Enroleeyone", targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", className = "sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign.Enroleeyone")
    @WebMethod(operationName = "Enroleeyone", action = "Initialisation")
    @ResponseWrapper(localName = "EnroleeyoneResponse", targetNamespace = "http://www.confiancefactory.com/WSDL_RASign/", className = "sn.gainde2000.pi.integration.signature.confiancefactory.wsdl_rasign.EnroleeyoneResponse")
    public java.lang.String enroleeyone(
        @WebParam(name = "prenom_nom", targetNamespace = "")
        java.lang.String prenomNom,
        @WebParam(name = "numero_cni", targetNamespace = "")
        java.lang.String numeroCni,
        @WebParam(name = "code_pin", targetNamespace = "")
        java.lang.String codePin,
        @WebParam(name = "scan_cni", targetNamespace = "")
        byte[] scanCni,
        @WebParam(name = "IdAppAppelant", targetNamespace = "")
        long idAppAppelant
    );
}
